# Generated by Django 5.2 on 2025-12-03 19:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicplace',
            name='date_end',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_partial_date]),
        ),
        migrations.AlterField(
            model_name='historicplace',
            name='date_start',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_partial_date]),
        ),
    ]
