# Generated by Django 5.2 on 2025-12-04 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historicplace_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewee_name', models.CharField(help_text='Name of the person being interviewed.', max_length=100)),
                ('interviewer_name', models.CharField(blank=True, help_text='Name of the person conducting the interview.', max_length=100)),
                ('brief_description', models.TextField(blank=True, help_text='Short description of the interview content.', validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('interview_date', models.DateField(help_text='Date when the interview was recorded.')),
                ('youtube_url', models.URLField(help_text='Public YouTube URL where the interview video is hosted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-interview_date', 'interviewee_name'],
                'indexes': [models.Index(fields=['interview_date'], name='core_histor_intervi_8c91f2_idx'), models.Index(fields=['interviewee_name'], name='core_histor_intervi_c07de5_idx')],
            },
        ),
    ]
